### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'camelize')

### ISSUE THREAD

**Issue by stwebyy** [dreamerslab/node.inflection#97]
# background
The error did not occur when using 1.13.4v.
After updating to 2.0.1v and removing @types/inflection from package.json, the error in the title occurred.

# repo
https://github.com/stwebyy/inflection-test

Error in `yarn run:inflecition`.

```
yarn run v1.22.19
$ esno index.ts
/Users/stwebyy/dev/inflection-test/index.ts:4
const upperCase = inflection.camelize(test);
                             ^


TypeError: Cannot read properties of undefined (reading 'camelize')
    at <anonymous> (/Users/stwebyy/dev/inflection-test/index.ts:4:30)
    at Object.<anonymous> (/Users/stwebyy/dev/inflection-test/index.ts:5:22)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.F (/Users/stwebyy/dev/inflection-test/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

# question
Is there something wrong with my procedure?

**Comment by p-kuen** [comment]
Hello, thanks for creating the issue.
Can you try importing the package in ESM-style?

```ts
import {camelize} from 'inflection'
```

Importing it this way should do the trick. Are you importing with `require`?

**Comment by stwebyy** [comment]
Thanks for the answer!
Several repositories I am working on use import, and it looks like `import` is better than `require`.
I will share this with other developers when inflection update.
